contact_links:
    - name: Questions and Help
      url: https://github.com/PrismJS/prism/discussions/categories/q-a
      about: This issue tracker is not for support questions. Please refer to the Prism's Discussion tab.
