/**
 * A record mapping the aliases of all known components to their respective ids.
 *
 * Note: This record is automatically generated by the build process.
 *
 * @type {Readonly<Partial<Record<string, string>>>}
 */
const knownAliases = /*aliases_placeholder[*/{}/*]*/;

/**
 * @param {string} name
 * @returns {string}
 */
export function resolveAlias(name) {
	return knownAliases[name] || name;
}
