/**
 * A list of the ids of all known languages.
 *
 * Note: This list is automatically generated by the build process.
 */
export const knownLanguages: readonly string[] = /* all_languages_placeholder[ */[]/* ] */;
