/**
 * A record mapping the id or alias of a given language to the title of that id or alias.
 *
 * Note: This record is automatically generated by the build process.
 *
 * @type {Readonly<Partial<Record<string, string>>>}
 */
export const knownTitles = /*languages_placeholder[*/{}/*]*/;
