name: Rebuild Website

on:
  push:
    branches:
      # FIXME: Use the main branch when v2 is out
      - v2

jobs:
  trigger-rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Build Hook
        run: curl -X POST -d "{}" "https://api.netlify.com/build_hooks/67ee8bcdb6033e6afa7eec48?trigger_title=The+Prism+code+has+been+updated"
